### ISSUE TITLE
OpenID Connect Add Provider does not work

### ISSUE THREAD

**Issue by nicolaescu** [rwth-acis/ROLE-SDK#16]
One can create a new provider by adding OIDC configuration URL, for example: 
https://api.learning-layers.eu/o/oauth2/.well-known/openid-configuration (THIS NEED TO BE PREDEFINED, or at least have an autocomplete).

The new provider remains there as long as the ROLE SDK runs. Upon new start, the added provider is undefined. This should not be the case. Also, after new start one cannot add a new provider, it will always be undefined, until the database is erased and the project restarted.

**Comment by adabru** [comment]
There were two string-comparison using '=='. Changing it to 'equals(…)' seems to solve the issue.
