### ISSUE TITLE
OpenID access_token in user resource "http://xmlns.com/foaf/0.1/openid" is not updated when it is refreshed

### ISSUE THREAD

**Issue by mabdh** [rwth-acis/ROLE-SDK#19]
I tried to create a widget that obtains user credential from OpenID in ROLE space. However, the access_token of OpenID in user resource is not updated once it was expired and refreshed. The access_token is needed to be able to communicate with las2peer and extend the user in ROLE space with las2peer UserAgent.
Is it a bug or is it by design?

**Comment by adabru** [comment]
That may be related to this bug https://github.com/rwth-acis/ROLE-SDK/issues/18 . Is this problem urgent?

**Comment by mabdh** [comment]
@adabru Yes, it is urgent for me. I am currently waiting for the bug to be fixed in order to continue my master thesis. I am stuck in this part. I have been trying to fix the bug by myself for this week (digging inside conserve service) but I still don't know what happen inside. It will be great if someone fix the bug soon.
Thank you.

**Comment by adabru** [comment]
Ok, I changed the code so that access_token is stored in the database on every user login. So far it was only done on first login:
```
Concept user = store().in(userContext).sub().get(userName);
if (user == null) { /* create user and store access_token */ }
```
Changes are in branch *feature/develop-noDUI-oidcRefresh*.

Do you build role yourself or do you use http://role-sandbox.eu?

**Comment by mabdh** [comment]
Thank you for your help.
I am currently build role by myself and intended to deploy the branch feature/develop-noDUI-oidcRefresh for my demo. I may not use http://role-sandbox.eu because it has some errors. However, I have some problems when trying to deploy the role space to ubuntu server. I changed jetty.host in start.sh file to 0.0.0.0 but some database exceptions appear.
Do you have any idea about deploying the role sdk?

**Comment by adabru** [comment]
Hm, my deployment method on Ubuntu (not Ubuntu Server) is:
- open terminal
- └▪time git clone git://github.com/rwth-acis/ROLE-SDK↵ ⏲21
- └▪git remote set-url origin git@github.com:rwth-acis/ROLE-SDK.git↵
- └▪git checkout feature/develop-noDUI-oidcRefresh↵
- change in ↑/assembly/src/main/assembly/sdk.xml :
```
<format>zip</format>
<format>tar.gz</format>
```
to
```
<!--<format>zip</format>-->
<!--<format>tar.gz</format>-->
<format>dir</format>
```
- └▪mvn package↵ ⏲1:00 (first time, then ⏲37)
- └▪[assembly/target/role-m10-sdk/role-m10-sdk] chmod +x ./bin/start.sh↵
- └▪[assembly/target/role-m10-sdk/role-m10-sdk] ./bin/start.sh↵
- browser at http://127.0.0.1:8073/

At the moment the jsdoc-toolkit version 2.4.0 is not supported so the build breaks (some months ago it worked). I'll comment it out. I can look tomorrow what errors my deployment will show if I change address 127.0.0.1 to 0.0.0.0. Don't know if 0.0.0.0 works, google said to me it's a broadcast address. With 127.0.0.1 it should be working.

**Comment by mabdh** [comment]
Your development method is exactly same with me. I also successfully access the role locally via 127.0.0.1:8073.
But, when I use ubuntu server (to simulate the deployment) in virtual box (to be able to be accessed remotely), run role sdk there, bridge the network adapter, I got database exception error.

I also was looking for the answer about how to deploy jetty so it could be accessed remotely, it said the jetty.host should be set to 0.0.0.0. 

Yes, there is a problem with jsdoc toolkit source address. I already changed the address to get jsdoctoolkit zip in build.xml in assembly folder and t works.

**Comment by mabdh** [comment]
Your development method is exactly same with me. I also successfully access the role locally via 127.0.0.1:8073.
But, when I use ubuntu server (to simulate the deployment) in virtual box (to be able to be accessed remotely), run role sdk there, bridge the network adapter, I got database exception error.

I also was looking for the answer about how to deploy jetty so it could be accessed remotely, and google said the jetty.host should be set to 0.0.0.0. 

Yes, there is a problem with jsdoc toolkit source address. I already changed the address to get jsdoctoolkit zip in build.xml in assembly folder and t works.

**Comment by adabru** [comment]
Ok I tried it out. What I would suggest you is to delete the files `role-m10-sdk/bin/OpenAPPDB*` and then start the sdk again.
I also tried the bridged network adapter and could access (from host system) the sdk (running in guest).  I changed address 127.0.0.1 in `role-m10-sdk/bin/start.sh` to 192.168.178.54 in my case.

**Comment by adabru** [comment]
Ah and could you please tell me which address you use for the jsdoctoolkit?

**Comment by mabdh** [comment]
Hi @adabru ,
I tried what you suggest and it worked. Thank you !

For jsdoctoolkit, I use this link https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/jsdoc-toolkit/jsdoc_toolkit-2.4.0.zip .

It is actually based on this repo https://code.google.com/archive/p/jsdoc-toolkit/downloads , just right click on the file and copy link location.

**Comment by mabdh** [comment]
Hi @adabru ,

I tried to run the newest version of feature/develop-noDUI-oidcRefresh branch.

There are some problems when running mvn package.
1. In space-service, cannot resolve dependency caja r4487.
2. In ple (role-space), caja r4251.

But, I added caja dependecies in pom.xml from this repository : https://repository.jboss.org/nexus/content/groups/public/

After it is successfully built. I can run the ROLE sdk but this error occured after "Initialization completed" :

```
org.apache.shindig.auth.AuthenticationServletFilter doFilter
INFO: The input secure token or credential is malform and can not be parsed.
org.apache.shindig.auth.SecurityTokenException: org.apache.shindig.common.crypto.BlobCrypterException: Invalid token signature
```

**Comment by adabru** [comment]
Ok thank you for pointing me to the maven repositories, I added them now.

For me it works. Did you already try to again delete the `OpenAPPDB*` files?

**Comment by mabdh** [comment]
I already did what you have said before to delete OpenAPPDB* files. The problem occurs when I host all widgets in a space using dropbox.
The problem is avoidable when I host the widgets in github.

I already deployed to oidc refresh branch on http://gaudi.informatik.rwth-aachen.de:8073/

**Comment by mabdh** [comment]
Hi @adabru , I think it does not matter where we host the widgets, because I use github and this problem happens..
![unbenannt](https://cloud.githubusercontent.com/assets/4079709/18587154/bca0d1ec-7c20-11e6-8aaa-cf1a83000cf5.PNG)

**Comment by mabdh** [comment]
Hi, I think I figured out the problem. It is because I didn't build the SDK inside the server. I built it in my computer and copy the target folder to the server.
